### <<Health Check>>
### http
GET http://localhost:4000/api/_health-check

### curl
curl --location --request GET 'http://localhost:4000/api/_health-check'


### <<Create Single Movie>>
### http
POST http://localhost:4000/api/movies/create HTTP/1.1
Host: localhost:4000
Content-Type: application/json
Content-Length: 294

{
   "title": "The Movie Title",
   "year": "1900",
   "genres": ["abc", "def"],
   "director": "Boss Man",
   "actors": ["Billy Bob", "Bobby Jones"],
   "plot": "I'm lovin' it",
   "runtime": "123",
   "poster": {
      "image": "asdf",
      "fallback": "asdf"
   }
}

### curl
curl --location --request POST 'http://localhost:4000/api/movies/create' \
--header 'Content-Type: application/json' \
--data-raw '{
   "title": "The Movie Title",
   "year": "2002",
   "genres": ["abc", "def"],
   "director": "Boss Man",
   "actors": ["Billy Bob", "Bobby Jones"],
   "plot": "I'\''m lovin'\'' it",
   "runtime": "123",
   "poster": {
      "image": "asdf",
      "fallback": "asdf"
   }
}'


### <<Create All Movies>>
### http
POST /api/movies HTTP/1.1
Host: localhost:4000
Content-Type: application/json
Content-Length: 1149

[
   {
      "title": "The Movie Title1",
      "year": "2002",
      "genres": [
         "abc",
         "def"
      ],
      "director": "Boss Man",
      "actors": [
         "Billy Bob",
         "Bobby Jones"
      ],
      "plot": "I'm lovin' it",
      "runtime": "123",
      "poster": {
         "image": "asdf",
         "fallback": "asdf"
      }
   },
   {
      "title": "The Movie Title2",
      "year": "2002",
      "genres": [
         "abc",
         "def"
      ],
      "director": "Boss Man",
      "actors": [
         "Billy Bob",
         "Bobby Jones"
      ],
      "plot": "I'm lovin' it",
      "runtime": "123",
      "poster": {
         "image": "asdf",
         "fallback": "asdf"
      }
   },
   {
      "title": "The Movie Title3",
      "year": "2002",
      "genres": [
         "abc",
         "def"
      ],
      "director": "Boss Man",
      "actors": [
         "Billy Bob",
         "Bobby Jones"
      ],
      "plot": "I'm lovin' it",
      "runtime": "123",
      "poster": {
         "image": "asdf",
         "fallback": "asdf"
      }
   }
]

### curl
curl --location --request POST 'http://localhost:4000/api/movies' \
--header 'Content-Type: application/json' \
--data-raw '[
   {
      "title": "The Movie Title1",
      "year": "2002",
      "genres": [
         "abc",
         "def"
      ],
      "director": "Boss Man",
      "actors": [
         "Billy Bob",
         "Bobby Jones"
      ],
      "plot": "I'\''m lovin'\'' it",
      "runtime": "123",
      "poster": {
         "image": "asdf",
         "fallback": "asdf"
      }
   },
   {
      "title": "The Movie Title2",
      "year": "2002",
      "genres": [
         "abc",
         "def"
      ],
      "director": "Boss Man",
      "actors": [
         "Billy Bob",
         "Bobby Jones"
      ],
      "plot": "I'\''m lovin'\'' it",
      "runtime": "123",
      "poster": {
         "image": "asdf",
         "fallback": "asdf"
      }
   },
   {
      "title": "The Movie Title3",
      "year": "2002",
      "genres": [
         "abc",
         "def"
      ],
      "director": "Boss Man",
      "actors": [
         "Billy Bob",
         "Bobby Jones"
      ],
      "plot": "I'\''m lovin'\'' it",
      "runtime": "123",
      "poster": {
         "image": "asdf",
         "fallback": "asdf"
      }
   }
]'